import { contract } from './contract';
import { product } from './product';
import { packing_unit } from './packing_unit';
import { pu_sub_code } from './pu_sub_code';
import { lov_data } from './lov_data';
import { unit_code } from './unit_code';

export class contract_item {
    id: string;
    contract_id: string;
    contract: contract;
    item_no: number;
    product_id: string;
    product: product;
    crop_year_type: string;
    crop_year_input: number;
    crop_year: string;
    min_pola: number;
    max_moisture: number;
    min_colour: number;
    max_colour: number;
    adm_finalprice_flag: boolean;
    apply_licenses_flag: boolean;
    qty: number;
    qty_tcsc_us: number;
    shipment_qty: number;
    pu_code_id: string;
    pu_code: packing_unit;
    packing_qty: number;
    unit_name_eng_id: string;
    unit_name_eng: unit_code;
    pu_sub_code_id: string;
    pu_sub_code: pu_sub_code;
    shipment_period_from: Date;
    shipment_period_to: Date;
    shipment_option: string;
    price_type_id: string;
    price_type: lov_data;
    sugar_cost: number;
    packing_cost: number;
    unt_price: number;
    insurance_cost: number;
    freight_cost: number;
    net_price: number;
    price_desc: string;
    ad_quality: boolean;
    ad_quantity: boolean;
    ad_packing: boolean;
    ad_shipment: boolean;
    ad_price: boolean;
    record_status: boolean;
    created_by_id: string;
    created_date: Date;
    updated_by_id: string;
    updated_date: Date;
}
