import { party } from './party';
import { lov_data } from './lov_data';
import { shipment_to } from './shipment_to';
import { currency } from './currency';
import { shipment_term } from './shipment_term';
import { term_cond } from './term_cond';
import { contract_item } from './contract_item';
import { payment_term } from './payment_term';

export class contract {
    id: string;
    contract_no: string;
    contract_date: Date;
    contract_type: string;
    contract_ver: number;
    latest_flag: boolean;
    addendum_type_id: string;
    addendum_type: lov_data;
    addendum_no: string;
    addendum_date: Date;
    contract_status: string;
    contract_made_on_id: string;
    contract_made_on: lov_data;
    crop_year: string;
    seller_id: string;
    seller: party;
    group_factory_id: string;
    group_factory: lov_data;
    sugar_type_id: string;
    sugar_type: lov_data;
    buyer_contract_no: string;
    buyer_id: string;
    buyer: party;
    shipment_term_id: string;
    shipment_term: shipment_term;
    shipment_by: string;
    shipment_period_from: Date;
    shipment_period_to: Date;
    shipment_option: string;
    partial_shipment_option_id: string;
    partial_shipment_option: lov_data;
    shipment_to_id: string;
    shipment_to: shipment_to;
    pricing_method: number;
    payment_term_id: string;
    payment_term: payment_term;
    currency_id: string;
    currency: currency;
    exchange_rate: number;
    shipment_term_remark: string;
    product_remark: string;
    gen_term_condition_id: string;
    gen_term_condition: term_cond;
    gen_term_condition_desc: string;
    ad_buyer_contract_no: boolean;
    ad_buyer: boolean;
    ad_shipment_term: boolean;
    ad_shipment_option: boolean;
    ad_partial_shipment_opt: boolean;
    ad_shipment_to: boolean;
    ad_payment_term: boolean;
    ad_exchange_rate: boolean;
    ad_shipment_term_remark: boolean;
    ad_product_remark: boolean;
    ad_gen_term_condition: boolean;
    total_qty: number;
    total_shipment: number;
    record_status: boolean;
    created_by_id: string;
    created_date: Date;
    updated_by_id: string;
    updated_date: Date;

    ref_contract_no: string;
    //ref_contract: contract;
    contract_items: contract_item[];
}